name: workflow-1
on: [push]
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm lint
  test: 
    runs-on: ubuntu-latest
    needs: lint
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm test
  build: 
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm build