name: workflow-1
on: [push]
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm lint
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: npm test
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: build
        run: npm build